api-key:
geocoding:
    provider: bing  # -or- google
    bing-api-key: Al4K-FqvPXxTlsOZq3Hb1nXkmC93RyiSqszyzf2hXEVzzr8YsG6EeOS91j2H2iqh
    # google-api-key: AIzaSyCVFA6n6QjPlpZQJAX-VrvgGpXGL-fMcnA
    # https://developers.google.com/maps/documentation/geocoding/#api_key
    preferred-coords:
        "new york":
            lat: 40.757777777777775
            lon: -73.98583333333333
mongo-db:
    main:
        # db-name: centzy_web_production
        db-name: centzy2_development
        username:
        password: 
        host: 127.0.0.1
        port: 27017
    areas:
        # db-name: locality_web_production_areas
        # username: locality_web_05_2014
        # password: JvJ6XlTIE0nf9mnggPTu7EImHfH7RsuwekgD24F152WaSip85da
        # host: locality-web-production-areas.m0.mongolayer.com
        # port: 27017
        db-name: locality_web_development_areas
        username:
        password:
        host: 127.0.0.1
        port: 27017
    businesses:
        # db-name: centzy_web_production #_businesses
        db-name: locality_web_development_businesses
        username:
        password: 
        host: 127.0.0.1
        port: 27017
elastic-search:
    host: localhost     # 107.20.137.247
    port: 9300
    cluster-name: elasticsearch      # elasticsearch
