api-key:
geocoding:
    provider: bing
    bing-api-key: Al4K-FqvPXxTlsOZq3Hb1nXkmC93RyiSqszyzf2hXEVzzr8YsG6EeOS91j2H2iqh
    preferred-coords:
        "new york":
            lat: 40.757777777777775
            lon: -73.98583333333333
mongo-db:
    main:
        db-name: centzy2_development
        username:
        password: 
        host: 127.0.0.1
        port: 27017
    areas:
        db-name: locality_web_development_areas
        username:
        password:
        host: 127.0.0.1
        port: 27017
    businesses:
        db-name: locality_web_development_businesses
        username:
        password: 
        host: 127.0.0.1
        port: 27017
elastic-search:
    host: localhost
    port: 9300
    cluster-name: elasticsearch
