# FIXME: Add an api-key!
api-key: 
geocoding:
    provider: bing
    bing-api-key: Al4K-FqvPXxTlsOZq3Hb1nXkmC93RyiSqszyzf2hXEVzzr8YsG6EeOS91j2H2iqh
    preferred-coords:
        "new york":
            lat: 40.757777777777775
            lon: -73.98583333333333
mongo-db:
    main:
        db-name: centzy_web_production
        username: searchzy
        password: holyfuckifthisworksiliterallywillcrywithhappiness
        host: centzy-production.m0.mongolayer.com
        port: 27017
    areas:
        db-name: locality_web_production_areas
        username: searchzy
        password: holyfuckifthisworksiliterallywillcrywithhappiness
        host: locality-web-production-areas.m0.mongolayer.com
        port: 27017
    businesses:
        db-name: locality_web_production_businesses
        username: searchzy
        password: holyfuckifthisworksiliterallywillcrywithhappiness
        host: locality-web-production-businesses.m0.mongolayer.com
        port: 27017
elastic-search:
    host: localhost
    port: 9300
    cluster-name: elasticsearch
